# Site settings
title: _blank_
email: vazkats@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ignore
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  oxilgk

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 2 
paginate_path: "/blog/page:num/"
exclude: [vendor]

# Plugins
plugins: [jekyll-paginate]

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


